apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  labels:
    app: deployment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-api
  template:
    metadata:
      labels:
        app: deployment-api
    spec:
      containers:
      - name: deployment-api
        image: samirelhassan/fiap-tech-challenge-04-user-service:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1" 
            memory: "512Mi" 
          requests:
            cpu: "500m" 
            memory: "256Mi" 
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: POSTGRES_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: JWT_SECRET
        
        # Probes
        # startupProbe:
        #   httpGet:
        #     path: /health-start
        #     port: 3001
        #   failureThreshold: 30 
        #   periodSeconds: 10    
        #   initialDelaySeconds: 180 # becausa of the memory config 
        # readinessProbe:
        #   httpGet:
        #     path: /health-read
        #     port: 3001
        #   initialDelaySeconds: 180 # becausa of the memory config
        #   periodSeconds: 10
        #   failureThreshold: 3
        # livenessProbe:
        #   httpGet:
        #     path: /health-live
        #     port: 3001
        #   initialDelaySeconds: 180 # becausa of the memory config
        #   periodSeconds: 10
        #   failureThreshold: 5 
